export const REQUEST_LOGIN = "AUTH/REQUEST_LOGIN";
export const REQUEST_LOGON = "AUTH/REQUEST_LOGON";
export const SET_AUTH = "AUTH/SET_AUTH";
export const LOGOUT = "AUTH/LOGOUT";

export const REQUEST_USER = "USER/REQUEST_USER";
export const SET_USER = "USER/SET_USER";

export const REQUEST_CREATER = "CREATER/REQUEST_CREATER";
export const SET_CREATER = "CREATER/SET_CREATER";
export const REQUEST_CREATE_EVENT = 'CREATER/REQUEST_CREATE_EVENT'
export const REQUEST_CREATE_GROUP = 'CREATER/REQUEST_CREATE_GROUP'