export const auth = {
  SET_AUTH: "AUTH/SET_AUTH",
  LOGOUT: "AUTH/LOGOUT",
};
export const user = {
  SET_USER: "USER/SET_USER",
  ADD_EVENT: "USER/ADD_EVENT",
  ADD_GROUP_USER: "USER/ADD_GROUP",
};

export const creater = {
  SET_CREATER: "CREATER/SET_CREATER",
  ADD_EVENT: "CREATER/ADD_EVENT",
  ADD_GROUP: "CREATER/ADD_GROUP",
  ADD_GROUP_CREATER: "CREATER/ADD_GROUP_CREATER",
};

export const app = {
  SET_PAGE: "APP/SET_PAGE",
  SET_SCHEDULE_MOD: "APP/SET_SHEDULE_MOD",
  SET_SCHEDULE_TODAY: "APP/SET_SHEDULE_TODAY",
};
